### Introduction

In [1]:
import requests
response = requests.get('https://data.texas.gov/resource/naix-2893.json?location_address=2411%20GLENNA%20GOODACRE%20BLVD')
results = response.json()

In [2]:
import pandas as pd
results_df = pd.DataFrame(results)
results_df.head()

beer_receipts cover_charge_receipts inside_outside_city_limits_code_y_n  \
0           114                     0                                   Y   
1           115                     0                                   Y   
2           158                     0                                   Y   
3           208                     0                                   Y   
4           378                     0                                   Y   

  liquor_receipts           location_address location_city location_county  \
0              76  2411 GLENNA GOODACRE BLVD       LUBBOCK             152   
1             137  2411 GLENNA GOODACRE BLVD       LUBBOCK             152   
2             116  2411 GLENNA GOODACRE BLVD       LUBBOCK             152   
3             147  2411 GLENNA GOODACRE BLVD       LUBBOCK             152   
4             631  2411 GLENNA GOODACRE BLVD       LUBBOCK             152   

            location_name location_number location_state      ...       \
0  CHIPOTLE MEXICAN GRILL             104             TX      ...        
1  CHIPOTLE MEXICAN GRILL             104             TX      ...        
2  CHIPOTLE MEXICAN GRILL             104             TX      ...        
3  CHIPOTLE MEXICAN GRILL             104             TX      ...        
4  CHIPOTLE MEXICAN GRILL             104             TX      ...        

  tabc_permit_number      taxpayer_address taxpayer_city taxpayer_county  \
0           MB762148  8800 LYRA DR STE 150      COLUMBUS               0   
1           MB762148  8800 LYRA DR STE 150      COLUMBUS               0   
2           MB762148  8800 LYRA DR STE 150      COLUMBUS               0   
3           MB762148  8800 LYRA DR STE 150      COLUMBUS               0   
4           MB762148  8800 LYRA DR STE 150      COLUMBUS               0   

            taxpayer_name taxpayer_number taxpayer_state taxpayer_zip  \
0  CHIPOTLE TEXAS, L.L.C.     17429444858             OH        43240   
1  CHIPOTLE TEXAS, L.L.C.     17429444858             OH        43240   
2  CHIPOTLE TEXAS, L.L.C.     17429444858             OH        43240   
3  CHIPOTLE TEXAS, L.L.C.     17429444858             OH        43240   
4  CHIPOTLE TEXAS, L.L.C.     17429444858             OH        43240   

  total_receipts wine_receipts  
0            190             0  
1            252             0  
2            274             0  
3            355             0  
4           1009             0  

[5 rows x 23 columns]

In [3]:
results_df.shape

(102, 23)

In [4]:
top_three = results_df[0:3]
top_three

beer_receipts cover_charge_receipts inside_outside_city_limits_code_y_n  \
0           114                     0                                   Y   
1           115                     0                                   Y   
2           158                     0                                   Y   

  liquor_receipts           location_address location_city location_county  \
0              76  2411 GLENNA GOODACRE BLVD       LUBBOCK             152   
1             137  2411 GLENNA GOODACRE BLVD       LUBBOCK             152   
2             116  2411 GLENNA GOODACRE BLVD       LUBBOCK             152   

            location_name location_number location_state      ...       \
0  CHIPOTLE MEXICAN GRILL             104             TX      ...        
1  CHIPOTLE MEXICAN GRILL             104             TX      ...        
2  CHIPOTLE MEXICAN GRILL             104             TX      ...        

  tabc_permit_number      taxpayer_address taxpayer_city taxpayer_county  \
0           MB762148  8800 LYRA DR STE 150      COLUMBUS               0   
1           MB762148  8800 LYRA DR STE 150      COLUMBUS               0   
2           MB762148  8800 LYRA DR STE 150      COLUMBUS               0   

            taxpayer_name taxpayer_number taxpayer_state taxpayer_zip  \
0  CHIPOTLE TEXAS, L.L.C.     17429444858             OH        43240   
1  CHIPOTLE TEXAS, L.L.C.     17429444858             OH        43240   
2  CHIPOTLE TEXAS, L.L.C.     17429444858             OH        43240   

  total_receipts wine_receipts  
0            190             0  
1            252             0  
2            274             0  

[3 rows x 23 columns]

In [5]:
results_df.columns

Index(['beer_receipts', 'cover_charge_receipts',
       'inside_outside_city_limits_code_y_n', 'liquor_receipts',
       'location_address', 'location_city', 'location_county', 'location_name',
       'location_number', 'location_state', 'location_zip',
       'obligation_end_date_yyyymmdd', 'responsibility_begin_date_yyyymmdd',
       'tabc_permit_number', 'taxpayer_address', 'taxpayer_city',
       'taxpayer_county', 'taxpayer_name', 'taxpayer_number', 'taxpayer_state',
       'taxpayer_zip', 'total_receipts', 'wine_receipts'],
      dtype='object')

In [6]:
results_df[['obligation_end_date_yyyymmdd', 'responsibility_begin_date_yyyymmdd']].head(10)

obligation_end_date_yyyymmdd responsibility_begin_date_yyyymmdd
0      2019-01-31T00:00:00.000            2010-11-19T00:00:00.000
1      2019-02-28T00:00:00.000            2010-11-19T00:00:00.000
2      2019-03-31T00:00:00.000            2010-11-19T00:00:00.000
3      2019-04-30T00:00:00.000            2010-11-19T00:00:00.000
4      2014-03-31T00:00:00.000            2010-11-19T00:00:00.000
5      2013-10-31T00:00:00.000            2010-11-19T00:00:00.000
6      2016-06-30T00:00:00.000            2010-11-19T00:00:00.000
7      2012-01-31T00:00:00.000            2010-11-19T00:00:00.000
8      2012-03-31T00:00:00.000            2010-11-19T00:00:00.000
9      2018-02-28T00:00:00.000            2010-11-19T00:00:00.000

In [7]:
beer_and_liquor_df = results_df[['beer_receipts', 'liquor_receipts', 'total_receipts']].apply(pd.to_numeric)

In [8]:
beer_receipts = beer_and_liquor_df['beer_receipts'].to_numpy()

AttributeError: 'Series' object has no attribute 'to_numpy'

- As shown above, .to_numpy does not generate the array that I want. Hence, I used .as_matrix as below:

In [9]:
beer_receipts = beer_and_liquor_df['beer_receipts'].as_matrix()

C:\Users\Minyeong\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [10]:
beer_receipts

array([114, 115, 158, 208, 378, 409, 153, 346, 504, 162, 187, 515, 442,
       103, 429, 278, 158,   0,   0, 538, 297, 590, 438, 398, 115,   0,
       129, 535, 208, 313, 407,  93, 498, 394, 308, 615, 354, 381, 175,
       251, 160, 378, 517, 337, 460, 394, 196, 211, 323, 148, 149,  88,
       204, 777, 508, 128, 244, 251, 266, 381, 115, 147, 165, 434, 516,
       256, 396, 218, 315, 235, 160, 149, 187, 559, 410, 292, 650,  86,
       530, 142, 194, 187, 205, 527, 143, 584,  92, 249, 267, 171, 472,
       385, 643, 455, 185,  97, 367, 342, 497, 527, 310, 387], dtype=int64)

In [11]:
liquor_receipts = beer_and_liquor_df['liquor_receipts'].values

In [12]:
liquor_receipts

array([ 76, 137, 116, 147, 631, 560, 116,  81, 261, 147, 249, 615, 787,
        69, 682,  27,  78,   0,   0, 327, 334, 815, 409, 445,  31,   0,
       183, 302, 204, 656, 761,  59, 937, 185, 144, 315, 480, 602, 175,
       297, 163, 357, 935, 167, 189, 662, 241,  78, 189, 144, 114, 121,
        95, 514, 248, 118, 178, 161, 349, 486,  76, 128, 329, 252, 319,
       213, 488, 168, 595, 251, 139, 159, 161, 275, 319, 334, 340, 133,
       288,  75,  76, 172, 380, 252, 111, 342, 151, 280, 166, 149, 167,
       482, 302, 185, 185,  78, 383, 531, 180, 234, 144, 149], dtype=int64)

### Working with Vectors in Numpy

Let's assume that chipotle earns $.20$ in marginal profit for every dollar of liquor sold, and $.10$ of marginal profit for every dollar of beer sold.

Calculate the marginal profit for liquor for each month.

In [13]:
marginal_liquor = .20 * liquor_receipts
marginal_liquor[0:5]

# marginal_liquor[0:5]
# array([ 15.2,  27.4,  23.2,  29.4, 126.2])

array([ 15.2,  27.4,  23.2,  29.4, 126.2])

In [14]:
marginal_beer = .10 * beer_receipts
marginal_beer[0:5]

# marginal_beer[0:5]
# array([11.4, 11.5, 15.8, 20.8, 37.8])

array([11.4, 11.5, 15.8, 20.8, 37.8])

Now calculate the total marginal profit on all alcohol sales -- assume that beer and alcohol receipts are the only source of alcohol revenue.

In [15]:
total_margins = marginal_liquor + marginal_beer
total_margins
# Please check your own work for this one

array([ 26.6,  38.9,  39. ,  50.2, 164. , 152.9,  38.5,  50.8, 102.6,
        45.6,  68.5, 174.5, 201.6,  24.1, 179.3,  33.2,  31.4,   0. ,
         0. , 119.2,  96.5, 222. , 125.6, 128.8,  17.7,   0. ,  49.5,
       113.9,  61.6, 162.5, 192.9,  21.1, 237.2,  76.4,  59.6, 124.5,
       131.4, 158.5,  52.5,  84.5,  48.6, 109.2, 238.7,  67.1,  83.8,
       171.8,  67.8,  36.7,  70.1,  43.6,  37.7,  33. ,  39.4, 180.5,
       100.4,  36.4,  60. ,  57.3,  96.4, 135.3,  26.7,  40.3,  82.3,
        93.8, 115.4,  68.2, 137.2,  55.4, 150.5,  73.7,  43.8,  46.7,
        50.9, 110.9, 104.8,  96. , 133. ,  35.2, 110.6,  29.2,  34.6,
        53.1,  96.5, 103.1,  36.5, 126.8,  39.4,  80.9,  59.9,  46.9,
        80.6, 134.9, 124.7,  82.5,  55.5,  25.3, 113.3, 140.4,  85.7,
        99.5,  59.8,  68.5])

Calculate the percentage of revenue that goes towards marginal profits each month.

In [16]:
total_receipts = beer_and_liquor_df['total_receipts'].as_matrix()
total_receipts

C:\Users\Minyeong\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([ 190,  252,  274,  355, 1009,  969,  269,  427,  765,  309,  436,
       1130, 1229,  172, 1111,  305,  236,    0,    0,  865,  631, 1405,
        847,  843,  146,    0,  312,  837,  412,  969, 1168,  152, 1435,
        579,  452,  930,  834,  983,  350,  548,  323,  735, 1452,  504,
        649, 1056,  437,  289,  512,  292,  263,  209,  299, 1291,  756,
        246,  422,  412,  615,  867,  191,  275,  494,  686,  835,  469,
        884,  386,  910,  486,  299,  308,  348,  834,  729,  626,  990,
        219,  818,  217,  270,  359,  585,  779,  254,  926,  243,  529,
        433,  320,  639,  867,  945,  640,  370,  175,  750,  873,  677,
        761,  454,  536], dtype=int64)

In [17]:
margin_percentage = total_margins / total_receipts

margin_percentage[0:3]

# margin_percentage[0:3]
# array([0.14      , 0.15436508, 0.14233577])

C:\Users\Minyeong\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([0.14      , 0.15436508, 0.14233577])

If we look at the array, there are three nan entries.

In [18]:
import numpy as np

np.argwhere(np.isnan(margin_percentage))

# np.argwhere(np.isnan(margin_percentage))
# array([[17],
#        [18],
#        [25]])

array([[17],
       [18],
       [25]], dtype=int64)

Why do you think that is?  Show your reasoning in code.

- As shown below, total_receipts values for index number 17, 18, 25 are all 0. Hence, (total_margins / total_receipts) is not a number (nan).

In [19]:
total_receipts

array([ 190,  252,  274,  355, 1009,  969,  269,  427,  765,  309,  436,
       1130, 1229,  172, 1111,  305,  236,    0,    0,  865,  631, 1405,
        847,  843,  146,    0,  312,  837,  412,  969, 1168,  152, 1435,
        579,  452,  930,  834,  983,  350,  548,  323,  735, 1452,  504,
        649, 1056,  437,  289,  512,  292,  263,  209,  299, 1291,  756,
        246,  422,  412,  615,  867,  191,  275,  494,  686,  835,  469,
        884,  386,  910,  486,  299,  308,  348,  834,  729,  626,  990,
        219,  818,  217,  270,  359,  585,  779,  254,  926,  243,  529,
        433,  320,  639,  867,  945,  640,  370,  175,  750,  873,  677,
        761,  454,  536], dtype=int64)

In [20]:
indices =[17, 18, 25] 
np.take(total_receipts, indices) #indexing

array([0, 0, 0], dtype=int64)

In [21]:
total_margins[indices] / total_receipts[indices]

C:\Users\Minyeong\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, nan, nan])

- As shown above code, dividing the total_margins (numerator) at index number of 17, 18, 25 by total_receipts (denominator or divisor) at index number of 17, 18, 25 respectively generates nan(not a number) because the total_receipts value (denominator or divisor) for each index number is 0.

### Summary

Great job!  In this lesson we practiced adding and multiplying vectors in numpy.