### Introduction

In [1]:
import requests
response = requests.get('https://data.texas.gov/resource/naix-2893.json?location_address=2411%20GLENNA%20GOODACRE%20BLVD')
results = response.json()

In [2]:
import pandas as pd

In [3]:
type(results)

list

In [4]:
results

[{'taxpayer_number': '17429444858',
  'taxpayer_name': 'CHIPOTLE TEXAS, L.L.C.',
  'taxpayer_address': '8800 LYRA DR STE 150',
  'taxpayer_city': 'COLUMBUS',
  'taxpayer_state': 'OH',
  'taxpayer_zip': '43240',
  'taxpayer_county': '0',
  'location_number': '104',
  'location_name': 'CHIPOTLE MEXICAN GRILL',
  'location_address': '2411 GLENNA GOODACRE BLVD',
  'location_city': 'LUBBOCK',
  'location_state': 'TX',
  'location_zip': '79401',
  'location_county': '152',
  'inside_outside_city_limits_code_y_n': 'Y',
  'tabc_permit_number': 'MB762148',
  'responsibility_begin_date_yyyymmdd': '2010-11-19T00:00:00.000',
  'obligation_end_date_yyyymmdd': '2019-01-31T00:00:00.000',
  'liquor_receipts': '76',
  'wine_receipts': '0',
  'beer_receipts': '114',
  'cover_charge_receipts': '0',
  'total_receipts': '190'},
 {'taxpayer_number': '17429444858',
  'taxpayer_name': 'CHIPOTLE TEXAS, L.L.C.',
  'taxpayer_address': '8800 LYRA DR STE 150',
  'taxpayer_city': 'COLUMBUS',
  'taxpayer_state': 'OH

In [5]:
results_df = pd.DataFrame(results)

In [6]:
results_df.head()

beer_receipts cover_charge_receipts inside_outside_city_limits_code_y_n  \
0           114                     0                                   Y   
1           115                     0                                   Y   
2           158                     0                                   Y   
3           208                     0                                   Y   
4           378                     0                                   Y   

  liquor_receipts           location_address location_city location_county  \
0              76  2411 GLENNA GOODACRE BLVD       LUBBOCK             152   
1             137  2411 GLENNA GOODACRE BLVD       LUBBOCK             152   
2             116  2411 GLENNA GOODACRE BLVD       LUBBOCK             152   
3             147  2411 GLENNA GOODACRE BLVD       LUBBOCK             152   
4             631  2411 GLENNA GOODACRE BLVD       LUBBOCK             152   

            location_name location_number location_state      ...       \
0  CHIPOTLE MEXICAN GRILL             104             TX      ...        
1  CHIPOTLE MEXICAN GRILL             104             TX      ...        
2  CHIPOTLE MEXICAN GRILL             104             TX      ...        
3  CHIPOTLE MEXICAN GRILL             104             TX      ...        
4  CHIPOTLE MEXICAN GRILL             104             TX      ...        

  tabc_permit_number      taxpayer_address taxpayer_city taxpayer_county  \
0           MB762148  8800 LYRA DR STE 150      COLUMBUS               0   
1           MB762148  8800 LYRA DR STE 150      COLUMBUS               0   
2           MB762148  8800 LYRA DR STE 150      COLUMBUS               0   
3           MB762148  8800 LYRA DR STE 150      COLUMBUS               0   
4           MB762148  8800 LYRA DR STE 150      COLUMBUS               0   

            taxpayer_name taxpayer_number taxpayer_state taxpayer_zip  \
0  CHIPOTLE TEXAS, L.L.C.     17429444858             OH        43240   
1  CHIPOTLE TEXAS, L.L.C.     17429444858             OH        43240   
2  CHIPOTLE TEXAS, L.L.C.     17429444858             OH        43240   
3  CHIPOTLE TEXAS, L.L.C.     17429444858             OH        43240   
4  CHIPOTLE TEXAS, L.L.C.     17429444858             OH        43240   

  total_receipts wine_receipts  
0            190             0  
1            252             0  
2            274             0  
3            355             0  
4           1009             0  

[5 rows x 23 columns]

In [7]:
top_three = results_df[0:3]
top_three

beer_receipts cover_charge_receipts inside_outside_city_limits_code_y_n  \
0           114                     0                                   Y   
1           115                     0                                   Y   
2           158                     0                                   Y   

  liquor_receipts           location_address location_city location_county  \
0              76  2411 GLENNA GOODACRE BLVD       LUBBOCK             152   
1             137  2411 GLENNA GOODACRE BLVD       LUBBOCK             152   
2             116  2411 GLENNA GOODACRE BLVD       LUBBOCK             152   

            location_name location_number location_state      ...       \
0  CHIPOTLE MEXICAN GRILL             104             TX      ...        
1  CHIPOTLE MEXICAN GRILL             104             TX      ...        
2  CHIPOTLE MEXICAN GRILL             104             TX      ...        

  tabc_permit_number      taxpayer_address taxpayer_city taxpayer_county  \
0           MB762148  8800 LYRA DR STE 150      COLUMBUS               0   
1           MB762148  8800 LYRA DR STE 150      COLUMBUS               0   
2           MB762148  8800 LYRA DR STE 150      COLUMBUS               0   

            taxpayer_name taxpayer_number taxpayer_state taxpayer_zip  \
0  CHIPOTLE TEXAS, L.L.C.     17429444858             OH        43240   
1  CHIPOTLE TEXAS, L.L.C.     17429444858             OH        43240   
2  CHIPOTLE TEXAS, L.L.C.     17429444858             OH        43240   

  total_receipts wine_receipts  
0            190             0  
1            252             0  
2            274             0  

[3 rows x 23 columns]

In [8]:
top_three.columns

Index(['beer_receipts', 'cover_charge_receipts',
       'inside_outside_city_limits_code_y_n', 'liquor_receipts',
       'location_address', 'location_city', 'location_county', 'location_name',
       'location_number', 'location_state', 'location_zip',
       'obligation_end_date_yyyymmdd', 'responsibility_begin_date_yyyymmdd',
       'tabc_permit_number', 'taxpayer_address', 'taxpayer_city',
       'taxpayer_county', 'taxpayer_name', 'taxpayer_number', 'taxpayer_state',
       'taxpayer_zip', 'total_receipts', 'wine_receipts'],
      dtype='object')

In [9]:
beer_and_liquor_df = results_df[['beer_receipts', 'liquor_receipts', 'total_receipts']].apply(pd.to_numeric)

In [10]:
beer_and_liquor_df.head(3)

beer_receipts  liquor_receipts  total_receipts
0            114               76             190
1            115              137             252
2            158              116             274

In [11]:
import numpy as np

beer_receipts = beer_and_liquor_df['beer_receipts'].to_numpy()

AttributeError: 'Series' object has no attribute 'to_numpy'

- As shown above, by using .to_numpy() I got error. Hence, I used .as_matrix() or .values as blow:

In [12]:
beer_receipts = beer_and_liquor_df['beer_receipts'].as_matrix()
beer_receipts

C:\Users\Minyeong\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([114, 115, 158, 208, 378, 409, 153, 346, 504, 162, 187, 515, 442,
       103, 429, 278, 158,   0,   0, 538, 297, 590, 438, 398, 115,   0,
       129, 535, 208, 313, 407,  93, 498, 394, 308, 615, 354, 381, 175,
       251, 160, 378, 517, 337, 460, 394, 196, 211, 323, 148, 149,  88,
       204, 777, 508, 128, 244, 251, 266, 381, 115, 147, 165, 434, 516,
       256, 396, 218, 315, 235, 160, 149, 187, 559, 410, 292, 650,  86,
       530, 142, 194, 187, 205, 527, 143, 584,  92, 249, 267, 171, 472,
       385, 643, 455, 185,  97, 367, 342, 497, 527, 310, 387], dtype=int64)

In [13]:
beer_receipts

array([114, 115, 158, 208, 378, 409, 153, 346, 504, 162, 187, 515, 442,
       103, 429, 278, 158,   0,   0, 538, 297, 590, 438, 398, 115,   0,
       129, 535, 208, 313, 407,  93, 498, 394, 308, 615, 354, 381, 175,
       251, 160, 378, 517, 337, 460, 394, 196, 211, 323, 148, 149,  88,
       204, 777, 508, 128, 244, 251, 266, 381, 115, 147, 165, 434, 516,
       256, 396, 218, 315, 235, 160, 149, 187, 559, 410, 292, 650,  86,
       530, 142, 194, 187, 205, 527, 143, 584,  92, 249, 267, 171, 472,
       385, 643, 455, 185,  97, 367, 342, 497, 527, 310, 387], dtype=int64)

In [14]:
liquor_receipts = beer_and_liquor_df['liquor_receipts'].as_matrix()
liquor_receipts

C:\Users\Minyeong\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([ 76, 137, 116, 147, 631, 560, 116,  81, 261, 147, 249, 615, 787,
        69, 682,  27,  78,   0,   0, 327, 334, 815, 409, 445,  31,   0,
       183, 302, 204, 656, 761,  59, 937, 185, 144, 315, 480, 602, 175,
       297, 163, 357, 935, 167, 189, 662, 241,  78, 189, 144, 114, 121,
        95, 514, 248, 118, 178, 161, 349, 486,  76, 128, 329, 252, 319,
       213, 488, 168, 595, 251, 139, 159, 161, 275, 319, 334, 340, 133,
       288,  75,  76, 172, 380, 252, 111, 342, 151, 280, 166, 149, 167,
       482, 302, 185, 185,  78, 383, 531, 180, 234, 144, 149], dtype=int64)

In [15]:
liquor_receipts

array([ 76, 137, 116, 147, 631, 560, 116,  81, 261, 147, 249, 615, 787,
        69, 682,  27,  78,   0,   0, 327, 334, 815, 409, 445,  31,   0,
       183, 302, 204, 656, 761,  59, 937, 185, 144, 315, 480, 602, 175,
       297, 163, 357, 935, 167, 189, 662, 241,  78, 189, 144, 114, 121,
        95, 514, 248, 118, 178, 161, 349, 486,  76, 128, 329, 252, 319,
       213, 488, 168, 595, 251, 139, 159, 161, 275, 319, 334, 340, 133,
       288,  75,  76, 172, 380, 252, 111, 342, 151, 280, 166, 149, 167,
       482, 302, 185, 185,  78, 383, 531, 180, 234, 144, 149], dtype=int64)

In [16]:
total_receipts = beer_and_liquor_df['total_receipts'].values
total_receipts

array([ 190,  252,  274,  355, 1009,  969,  269,  427,  765,  309,  436,
       1130, 1229,  172, 1111,  305,  236,    0,    0,  865,  631, 1405,
        847,  843,  146,    0,  312,  837,  412,  969, 1168,  152, 1435,
        579,  452,  930,  834,  983,  350,  548,  323,  735, 1452,  504,
        649, 1056,  437,  289,  512,  292,  263,  209,  299, 1291,  756,
        246,  422,  412,  615,  867,  191,  275,  494,  686,  835,  469,
        884,  386,  910,  486,  299,  308,  348,  834,  729,  626,  990,
        219,  818,  217,  270,  359,  585,  779,  254,  926,  243,  529,
        433,  320,  639,  867,  945,  640,  370,  175,  750,  873,  677,
        761,  454,  536], dtype=int64)

In [17]:
total_receipts

array([ 190,  252,  274,  355, 1009,  969,  269,  427,  765,  309,  436,
       1130, 1229,  172, 1111,  305,  236,    0,    0,  865,  631, 1405,
        847,  843,  146,    0,  312,  837,  412,  969, 1168,  152, 1435,
        579,  452,  930,  834,  983,  350,  548,  323,  735, 1452,  504,
        649, 1056,  437,  289,  512,  292,  263,  209,  299, 1291,  756,
        246,  422,  412,  615,  867,  191,  275,  494,  686,  835,  469,
        884,  386,  910,  486,  299,  308,  348,  834,  729,  626,  990,
        219,  818,  217,  270,  359,  585,  779,  254,  926,  243,  529,
        433,  320,  639,  867,  945,  640,  370,  175,  750,  873,  677,
        761,  454,  536], dtype=int64)

### Working with Vectors in Numpy

First, let's use our knowledge of numpy and vectors to select specific data.

Start by selecting the first three entries for liquor receipts.

In [18]:
liquor_receipts

array([ 76, 137, 116, 147, 631, 560, 116,  81, 261, 147, 249, 615, 787,
        69, 682,  27,  78,   0,   0, 327, 334, 815, 409, 445,  31,   0,
       183, 302, 204, 656, 761,  59, 937, 185, 144, 315, 480, 602, 175,
       297, 163, 357, 935, 167, 189, 662, 241,  78, 189, 144, 114, 121,
        95, 514, 248, 118, 178, 161, 349, 486,  76, 128, 329, 252, 319,
       213, 488, 168, 595, 251, 139, 159, 161, 275, 319, 334, 340, 133,
       288,  75,  76, 172, 380, 252, 111, 342, 151, 280, 166, 149, 167,
       482, 302, 185, 185,  78, 383, 531, 180, 234, 144, 149], dtype=int64)

In [19]:
selected_liquor = liquor_receipts[0:3] 
selected_liquor
# array([ 76, 137, 116])

array([ 76, 137, 116], dtype=int64)

Select all but the first three entries for beer reciepts.

In [20]:
beer_receipts

array([114, 115, 158, 208, 378, 409, 153, 346, 504, 162, 187, 515, 442,
       103, 429, 278, 158,   0,   0, 538, 297, 590, 438, 398, 115,   0,
       129, 535, 208, 313, 407,  93, 498, 394, 308, 615, 354, 381, 175,
       251, 160, 378, 517, 337, 460, 394, 196, 211, 323, 148, 149,  88,
       204, 777, 508, 128, 244, 251, 266, 381, 115, 147, 165, 434, 516,
       256, 396, 218, 315, 235, 160, 149, 187, 559, 410, 292, 650,  86,
       530, 142, 194, 187, 205, 527, 143, 584,  92, 249, 267, 171, 472,
       385, 643, 455, 185,  97, 367, 342, 497, 527, 310, 387], dtype=int64)

In [21]:
selected_beer = beer_receipts[3:]
selected_beer[0]
# selected_beer[0]
# 208

208

### Adding Vectors

We would like to add up the beer and liquor receipts for this chipotle location.  

Calculated the combined receipts for the first three entries of liquor and beer.

In [22]:
three_liquor = liquor_receipts[0:3]
three_liquor

array([ 76, 137, 116], dtype=int64)

In [23]:
three_beer = beer_receipts[0:3]
three_beer

array([114, 115, 158], dtype=int64)

In [24]:
three_liquor + three_beer

array([190, 252, 274], dtype=int64)

In [25]:
combined_receipts = three_liquor + three_beer
combined_receipts
# array([190, 252, 274])

array([190, 252, 274], dtype=int64)

We can confirm that it this combination also equals the total receipts for the first three entries.

In [26]:
total_receipts[:3]

array([190, 252, 274], dtype=int64)

In [27]:
len(total_receipts)

102

In [28]:
len(liquor_receipts)

102

In [29]:
len(beer_receipts)

102

Finally, use vector operations to calculate the difference between beer receipts and liquor receipts each month.

In [30]:
difference_of_beer_and_liquor = beer_receipts - liquor_receipts
difference_of_beer_and_liquor
# array([  38,  -22,   42,   61, -253, -151,   37,  265,  243,   15,  -62,
#        -100, -345,   34, -253,  251,   80,    0,    0,  211,  -37, -225,
#          29,  -47,   84,    0,  -54,  233,    4, -343, -354,   34, -439,
#         209,  164,  300, -126, -221,    0,  -46,   -3,   21, -418,  170,
#         271, -268,  -45,  133,  134,    4,   35,  -33,  109,  263,  260,
#          10,   66,   90,  -83, -105,   39,   19, -164,  182,  197,   43,
#         -92,   50, -280,  -16,   21,  -10,   26,  284,   91,  -42,  310,
#         -47,  242,   67,  118,   15, -175,  275,   32,  242,  -59,  -31,
#         101,   22,  305,  -97,  341,  270,    0,   19,  -16, -189,  317,
#         293,  166,  238])

array([  38,  -22,   42,   61, -253, -151,   37,  265,  243,   15,  -62,
       -100, -345,   34, -253,  251,   80,    0,    0,  211,  -37, -225,
         29,  -47,   84,    0,  -54,  233,    4, -343, -354,   34, -439,
        209,  164,  300, -126, -221,    0,  -46,   -3,   21, -418,  170,
        271, -268,  -45,  133,  134,    4,   35,  -33,  109,  263,  260,
         10,   66,   90,  -83, -105,   39,   19, -164,  182,  197,   43,
        -92,   50, -280,  -16,   21,  -10,   26,  284,   91,  -42,  310,
        -47,  242,   67,  118,   15, -175,  275,   32,  242,  -59,  -31,
        101,   22,  305,  -97,  341,  270,    0,   19,  -16, -189,  317,
        293,  166,  238], dtype=int64)

Display the three amounts where beer sales most outpace liquor sales.

In [31]:
import numpy as np

diff1 =  beer_receipts - liquor_receipts

beer_more_than_liquor = np.sort(diff1)[::-1] #reversing the sort
print(beer_more_than_liquor)

beer_more_than_liquor[0:3]
                     
# array([341, 317, 310])

[ 341  317  310  305  300  293  284  275  271  270  265  263  260  251
  243  242  242  238  233  211  209  197  182  170  166  164  134  133
  118  109  101   91   90   84   80   67   66   61   50   43   42   39
   38   37   35   34   34   32   29   26   22   21   21   19   19   15
   15   10    4    4    0    0    0    0    0   -3  -10  -16  -16  -22
  -31  -33  -37  -42  -45  -46  -47  -47  -54  -59  -62  -83  -92  -97
 -100 -105 -126 -151 -164 -175 -189 -221 -225 -253 -253 -268 -280 -343
 -345 -354 -418 -439]


array([341, 317, 310], dtype=int64)

In [32]:
liquor_more_than_beer = beer_more_than_liquor[::-1] #reversing the array
print(liquor_more_than_beer)

liquor_more_than_beer[0:3]

# array([-439, -418, -354])

[-439 -418 -354 -345 -343 -280 -268 -253 -253 -225 -221 -189 -175 -164
 -151 -126 -105 -100  -97  -92  -83  -62  -59  -54  -47  -47  -46  -45
  -42  -37  -33  -31  -22  -16  -16  -10   -3    0    0    0    0    0
    4    4   10   15   15   19   19   21   21   22   26   29   32   34
   34   35   37   38   39   42   43   50   61   66   67   80   84   90
   91  101  109  118  133  134  164  166  170  182  197  209  211  233
  238  242  242  243  251  260  263  265  270  271  275  284  293  300
  305  310  317  341]


array([-439, -418, -354], dtype=int64)

### Summary

Great job!  In this lesson we practiced selecting entries from vectors, and adding vectors.